### ISSUE TITLE
`select-keys` doesn't work

### ISSUE THREAD

**Issue by pharcosyle** [lokke-org/lokke#16]
It looks like someone misunderstood what Clojure's `select-keys` is supposed to do or copy/pasted too quickly because the implementation is totally off, it should be looping/folding over the passed keys and assoc'ing the corresponding passed map's entries, if present, into a new map.

I started using lokke yesterday and don't understand your internal functions (yet?) or I'd have written a pull request.

**Comment by rlbdv** [comment]
Updated; hopefully got it closer to right this time.

Thanks.
