### ISSUE TITLE
Why not using built in language support of guile ?

### ISSUE THREAD

**Issue by antoineB** [lokke-org/lokke#18]
https://www.gnu.org/software/guile/manual/html_node/Other-Languages.html

**Comment by rlbdv** [comment]
Hmm, if I understand you correctly, I believe it does.  You can follow the links from there to the [Writing New High-Level Languages section](https://www.gnu.org/software/guile/manual/html_node/Writing-New-High_002dLevel-Languages.html) and lokke's `(language LANG spec)` is [here](https://github.com/lokke-org/lokke/blob/main/mod/language/lokke/spec.scm).  Though there are definitely some things that still need improvement.

The [DESIGN document](https://github.com/lokke-org/lokke/blob/main/DESIGN.md) provides some additional information, and I'd be happy to discuss any of it in more detail on the [list or IRC](https://github.com/lokke-org/lokke#additional-contacts) if you like.

**Comment by antoineB** [comment]
Oh my bad.

**Comment by rlbdv** [comment]
antoineB ***@***.***> writes:

> Oh my bad.

No worries, and thanks for the interest.
